CREATE OR REPLACE TABLE CUSTOMER_PROFILE (
    CUSTOMER_ID STRING,
    EMAIL STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    REGION STRING,
    CUSTOMER_TYPE STRING,
    CONSENT_EMAIL BOOLEAN,
    CREATED_DATE TIMESTAMP_NTZ,
    UPDATED_DATE TIMESTAMP_NTZ
);
