CREATE OR REPLACE TABLE ENGAGEMENT_EVENTS (
    EVENT_ID STRING,
    CUSTOMER_ID STRING,
    EVENT_TYPE STRING,
    CHANNEL STRING,
    CAMPAIGN_ID STRING,
    PAGE_URL STRING,
    EVENT_TIMESTAMP TIMESTAMP_NTZ
);
