CREATE OR REPLACE VIEW CUSTOMER360_VIEW AS
SELECT
    c.CUSTOMER_ID,
    c.EMAIL,
    c.REGION,
    c.CUSTOMER_TYPE,
    c.CONSENT_EMAIL,
    COUNT(e.EVENT_ID) AS TOTAL_ENGAGEMENTS,
    MAX(e.EVENT_TIMESTAMP) AS LAST_ENGAGEMENT_DATE
FROM CUSTOMER_PROFILE c
LEFT JOIN ENGAGEMENT_EVENTS e
    ON c.CUSTOMER_ID = e.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.EMAIL,
    c.REGION,
    c.CUSTOMER_TYPE,
    c.CONSENT_EMAIL;
